export const mockedGetRecordsDataResponse: Api.Records.RecordsData[] = [
  {
    nameSurname: "Brenden Martinez",
    company: "Volutpat Nunc Associates",
    email: "iaculis@estMauris.org",
    date: "2021-03-23T21:00:00.000Z",
    country: "British Indian Ocean Territory",
    city: "Colwood",
  },
  {
    nameSurname: "Brenden Martinez",
    company: "Volutpat Nunc Associates",
    email: "iaculis@estMauris.org",
    date: "2021-03-23T21:00:00.000Z",
    country: "British Indian Ocean Territory",
    city: "Colwood",
  },
  {
    nameSurname: "Brenden Martinez",
    company: "Volutpat Nunc Associates",
    email: "iaculis@estMauris.org",
    date: "2021-03-23T21:00:00.000Z",
    country: "British Indian Ocean Territory",
    city: "Colwood",
  },
  {
    nameSurname: "Brenden Martinez",
    company: "Volutpat Nunc Associates",
    email: "iaculis@estMauris.org",
    date: "2021-03-23T21:00:00.000Z",
    country: "British Indian Ocean Territory",
    city: "Colwood",
  },
  {
    nameSurname: "Brenden Martinez",
    company: "Volutpat Nunc Associates",
    email: "iaculis@estMauris.org",
    date: "2021-03-23T21:00:00.000Z",
    country: "British Indian Ocean Territory",
    city: "Colwood",
  },
  {
    nameSurname: "Brenden Martinez",
    company: "Volutpat Nunc Associates",
    email: "iaculis@estMauris.org",
    date: "2021-03-23T21:00:00.000Z",
    country: "British Indian Ocean Territory",
    city: "Colwood",
  },
  {
    nameSurname: "Lunea Kinney",
    company: "Ornare Facilisis Eget Incorporated",
    email: "rutrum.eu@liberoMorbiaccumsan.ca",
    date: "2021-10-19T21:00:00.000Z",
    country: "Jordan",
    city: "Yorkton",
  },
  {
    nameSurname: "Hyacinth Vincent",
    company: "Duis Corporation",
    email: "iaculis.enim@magnaCrasconvallis.ca",
    date: "2022-06-27T21:00:00.000Z",
    country: "Eritrea",
    city: "Lyubertsy",
  },
  {
    nameSurname: "Brian Brooks",
    company: "Pellentesque Ut Ipsum Company",
    email: "lectus.Cum@egestasDuisac.edu",
    date: "2022-03-17T21:00:00.000Z",
    country: "Senegal",
    city: "Alto del Carmen",
  },
];
